name: Terragrunt CD

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The directory where Terragrunt should run'
        required: true
        type: string
      terraform-version:
        description: 'Version of Terraform to use'
        required: false
        type: string
        default: '1.6.2'
      use-local-backend:
        required: false
        type: boolean
        default: false
    secrets:
      TERRAGRUNT_GITHUB_TOKEN:
        required: false
      GCP_SERVICE_ACCOUNT_KEY:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.0/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      # - name: GCP Authentication
      #   if: secrets.GCP_SERVICE_ACCOUNT_KEY != ''
      #   run: |
      #     echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > gcp-key.json
      #     gcloud auth activate-service-account --key-file=gcp-key.json
      #     rm -f gcp-key.json

      - name: Download Terraform State (if local backend)
        if: ${{ inputs.use-local-backend }}
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: ${{ inputs.working-directory }}/terraform.tfstate

      - name: Terragrunt Init
        run: |
          cd ${{ inputs.working-directory }}
          terragrunt init
        env:
          TERRAGRUNT_GITHUB_TOKEN: ${{ secrets.TERRAGRUNT_GITHUB_TOKEN }}

      - name: Terragrunt Plan
        run: |
          cd ${{ inputs.working-directory }}
          terragrunt plan
        env:
          TERRAGRUNT_GITHUB_TOKEN: ${{ secrets.TERRAGRUNT_GITHUB_TOKEN }}

      - name: Terragrunt Apply
        run: |
          cd ${{ inputs.working-directory }}
          terragrunt apply -auto-approve
        env:
          TERRAGRUNT_GITHUB_TOKEN: ${{ secrets.TERRAGRUNT_GITHUB_TOKEN }}

      - name: Upload Terraform State (if local backend)
        if: ${{ inputs.use-local-backend }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: ${{ inputs.working-directory }}/terraform.tfstate
